# Site settings
title: rudimeyer.dk
email: hello@rudimeyer.dk
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rudimeyer.dk" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
github_username: rudimeyer
linkedin_url: https://www.linkedin.com/in/rudimeyerdk

# Build settings
markdown: kramdown
